### ISSUE TITLE
Example for pre-selected <option> does not show up

### ISSUE THREAD

**Issue by haikoschol** [OpenTechSchool/python-flask#9]
In forms.html, there's a bullet list about gotchas with select boxes (line 66 as of writing this ticket). The second item in the list contains an example for a pre-selected <option> element. This example does not show up in the rendered HTML. Creating code blocks by indenting apparently does not work inside lists. Putting triple-backticks around the example markup makes it show up, but does not wrap it in a <code> tag with the "xml" class applied. Thus no pretty.

I wanted to submit a pull request with a fix, but couldn't figure out the syntax to make it shiny. It's virtually impossible to tell the difference between me and Jon Snow when it comes to Markdown and Jekyll. So I resorted to writing this irritatingly prosaic bug report instead.

**Comment by Ivoz** [comment]
From http://daringfireball.net/projects/markdown/syntax: 

> To put a code block within a list item, the code block needs to be indented twice — 8 spaces or two tabs

Cheers for finding the missing example!
